name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: enable corepack
        run: corepack enable

      - name: use yarn 4
        run: corepack prepare yarn@4.6.0 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Lint code
        run: yarn lint

      - name: Stress test SEA256
        run: yarn stress:sea256
        env:
          NODE_ENV: production
